services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_DOMAIN: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 3;
        mc alias set local http://minio:9000 admin password;
        mc mb --ignore-existing local/warehouse;
        echo 'Bucket warehouse ready';
      "

  jupyter:
    image: quay.io/jupyter/pyspark-notebook:2025-12-31
    container_name: week04_jupyter
    depends_on:
      - minio
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./work/:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=bdm
      - PYSPARK_SUBMIT_ARGS=--packages org.apache.iceberg:iceberg-spark-runtime-4.0_2.13:1.10.1,org.apache.iceberg:iceberg-aws-bundle:1.10.1,org.apache.hadoop:hadoop-aws:3.3.4 pyspark-shell
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    command: >
      start-notebook.py
      --ServerApp.token=bdm
      --ServerApp.password=''
      --ServerApp.allow_origin='*'
      --ServerApp.allow_remote_access=True

volumes:
  minio-data: